# Generated by Django 5.1.2 on 2024-11-08 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0002_update_userupdate_follow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='desc',
            field=models.TextField(default=''),
        ),
    ]
